# Caragay, John Russell A.
# CPE32S1

<h2 style = "text-align: center;">Prelim Exam </h2>

<h3>Importing Necessary Libraries</h3>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

<h3>Importing Necessary Libraries</h3>

In [2]:
training_features = pd.read_csv('training_set_features.csv', index_col='respondent_id')
training_labels = pd.read_csv('training_set_labels.csv', index_col='respondent_id')
test_features = pd.read_csv('test_set_features.csv', index_col='respondent_id')
submission_format = pd.read_csv("submission_format.csv", index_col="respondent_id")

<h3>Data Analysis</h3>

In [3]:
data = training_features.join(training_labels)

In [4]:
data

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,...,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,h1n1_vaccine,seasonal_vaccine
respondent_id,,,,,,,,,,,,,,,,,,,,,
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,NaN,NaN,0,0
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe,0,1
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,...,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo,0,0
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,NaN,NaN,0,1
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,Own,Not in Labor Force,qufhixun,Non-MSA,0.0,0.0,NaN,NaN,0,0
26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,Rent,Employed,lzgpxyit,"MSA, Principle City",1.0,0.0,fcxhlnwr,cmhcxjea,0,0
26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,Own,NaN,lzgpxyit,"MSA, Not Principle City",0.0,0.0,NaN,NaN,0,1
26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,...,Rent,Employed,lrircsnp,Non-MSA,1.0,0.0,fcxhlnwr,haliazsg,0,0
26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Own,Not in Labor Force,mlyzmhmf,"MSA, Principle City",1.0,0.0,NaN,NaN,0,0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   h1n1_concern                 26615 non-null  float64
 1   h1n1_knowledge               26591 non-null  float64
 2   behavioral_antiviral_meds    26636 non-null  float64
 3   behavioral_avoidance         26499 non-null  float64
 4   behavioral_face_mask         26688 non-null  float64
 5   behavioral_wash_hands        26665 non-null  float64
 6   behavioral_large_gatherings  26620 non-null  float64
 7   behavioral_outside_home      26625 non-null  float64
 8   behavioral_touch_face        26579 non-null  float64
 9   doctor_recc_h1n1             24547 non-null  float64
 10  doctor_recc_seasonal         24547 non-null  float64
 11  chronic_med_condition        25736 non-null  float64
 12  child_under_6_months         25887 non-null  float64
 13  health_worker                25903 non-null  float64
 14  health_insurance             14433 non-null  float64
 15  opinion_h1n1_vacc_effective  26316 non-null  float64
 16  opinion_h1n1_risk            26319 non-null  float64
 17  opinion_h1n1_sick_from_vacc  26312 non-null  float64
 18  opinion_seas_vacc_effective  26245 non-null  float64
 19  opinion_seas_risk            26193 non-null  float64
 20  opinion_seas_sick_from_vacc  26170 non-null  float64
 21  age_group                    26707 non-null  object
 22  education                    25300 non-null  object
 23  race                         26707 non-null  object
 24  sex                          26707 non-null  object
 25  income_poverty               22284 non-null  object
 26  marital_status               25299 non-null  object
 27  rent_or_own                  24665 non-null  object
 28  employment_status            25244 non-null  object
 29  hhs_geo_region               26707 non-null  object
 30  census_msa                   26707 non-null  object
 31  household_adults             26458 non-null  float64
 32  household_children           26458 non-null  float64
 33  employment_industry          13377 non-null  object
 34  employment_occupation        13237 non-null  object
 35  h1n1_vaccine                 26707 non-null  int64
 36  seasonal_vaccine             26707 non-null  int64
dtypes: float64(23), int64(2), object(12)
memory usage: 8.8+ MB

<h3>Checking Null Entries in Training Features</h3>

In [6]:
#Making the training features' column to list
col_trainf = training_features.columns.tolist()

#Creating a list of total null per column
col_trainfnullsums = (training_features.isnull().sum()).to_list()

#Creating a list of average null per column
col_trainfnullpercent = (training_features.isnull().mean().round(5)*100).to_list()

#Creating a dataframe of the total sum and percent of null each column
null_trainf_Df = pd.DataFrame({'Column': col_trainf,'Null Entries': col_trainfnullsums,'Null Percent': col_trainfnullpercent})

In [7]:
null_trainf_Df

                         Column  Null Entries  Null Percent
0                  h1n1_concern            92         0.344
1                h1n1_knowledge           116         0.434
2     behavioral_antiviral_meds            71         0.266
3          behavioral_avoidance           208         0.779
4          behavioral_face_mask            19         0.071
5         behavioral_wash_hands            42         0.157
6   behavioral_large_gatherings            87         0.326
7       behavioral_outside_home            82         0.307
8         behavioral_touch_face           128         0.479
9              doctor_recc_h1n1          2160         8.088
10         doctor_recc_seasonal          2160         8.088
11        chronic_med_condition           971         3.636
12         child_under_6_months           820         3.070
13                health_worker           804         3.010
14             health_insurance         12274        45.958
15  opinion_h1n1_vacc_effective           391         1.464
16            opinion_h1n1_risk           388         1.453
17  opinion_h1n1_sick_from_vacc           395         1.479
18  opinion_seas_vacc_effective           462         1.730
19            opinion_seas_risk           514         1.925
20  opinion_seas_sick_from_vacc           537         2.011
21                    age_group             0         0.000
22                    education          1407         5.268
23                         race             0         0.000
24                          sex             0         0.000
25               income_poverty          4423        16.561
26               marital_status          1408         5.272
27                  rent_or_own          2042         7.646
28            employment_status          1463         5.478
29               hhs_geo_region             0         0.000
30                   census_msa             0         0.000
31             household_adults           249         0.932
32           household_children           249         0.932
33          employment_industry         13330        49.912
34        employment_occupation         13470        50.436

<h3>Checking Null Entries in Test Features</h3>

In [8]:
#Making the test features' column to list
col_testf = test_features.columns.tolist()

#Creating a list of total null per column
col_testfnullsums = (test_features.isnull().sum()).to_list()

#Creating a list of average null per column
col_testfnullpercent = (test_features.isnull().mean().round(5)*100).to_list()

#Creating a list of unique features per column
col_testfunique = test_features.nunique().to_list()

#Creating a dataframe of the total sum and percent of null each column
null_testf_Df = pd.DataFrame({'Column': col_testf,'Null Entries': col_testfnullsums,'Null Percentage': col_testfnullpercent,'Unique Entries': col_testfunique})

In [9]:
null_testf_Df

                         Column  Null Entries  Null Percentage  Unique Entries
0                  h1n1_concern            85            0.318               4
1                h1n1_knowledge           122            0.457               3
2     behavioral_antiviral_meds            79            0.296               2
3          behavioral_avoidance           213            0.798               2
4          behavioral_face_mask            19            0.071               2
5         behavioral_wash_hands            40            0.150               2
6   behavioral_large_gatherings            72            0.270               2
7       behavioral_outside_home            82            0.307               2
8         behavioral_touch_face           128            0.479               2
9              doctor_recc_h1n1          2160            8.087               2
10         doctor_recc_seasonal          2160            8.087               2
11        chronic_med_condition           932            3.490               2
12         child_under_6_months           813            3.044               2
13                health_worker           789            2.954               2
14             health_insurance         12228           45.784               2
15  opinion_h1n1_vacc_effective           398            1.490               5
16            opinion_h1n1_risk           380            1.423               5
17  opinion_h1n1_sick_from_vacc           375            1.404               5
18  opinion_seas_vacc_effective           452            1.692               5
19            opinion_seas_risk           499            1.868               5
20  opinion_seas_sick_from_vacc           521            1.951               5
21                    age_group             0            0.000               5
22                    education          1407            5.268               4
23                         race             0            0.000               4
24                          sex             0            0.000               2
25               income_poverty          4497           16.838               3
26               marital_status          1442            5.399               2
27                  rent_or_own          2036            7.623               2
28            employment_status          1471            5.508               3
29               hhs_geo_region             0            0.000              10
30                   census_msa             0            0.000               3
31             household_adults           225            0.842               4
32           household_children           225            0.842               4
33          employment_industry         13275           49.704              21
34        employment_occupation         13426           50.270              23

<h3>Filling Null Entries in Training Features and Test Features</h3>

In [10]:
#Checking the columns that has Null values from the dataframe created earlier
trainf_null_columns = null_trainf_Df[null_trainf_Df['Null Entries'] != 0].Column.to_list()

#Filling null entries in the training features
for col in trainf_null_columns:
        training_features[col]=training_features[col].fillna(training_features[col].mode()[0])

In [11]:
#training_features where null entries are removed
training_features

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
respondent_id,,,,,,,,,,,,,,,,,,,,,
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,Below Poverty,Not Married,Own,Not in Labor Force,oxchjgsf,Non-MSA,0.0,0.0,fcxhlnwr,xtkaffoo
1,3.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0.0,0.0,pxcmvdjn,xgwztkwe
2,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,qufhixun,"MSA, Not Principle City",2.0,0.0,rucpziij,xtkaffoo
3,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0.0,0.0,fcxhlnwr,xtkaffoo
4,2.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,qufhixun,"MSA, Not Principle City",1.0,0.0,wxleyezf,emcorrxb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26702,2.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Not in Labor Force,qufhixun,Non-MSA,0.0,0.0,fcxhlnwr,xtkaffoo
26703,1.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,"<= $75,000, Above Poverty",Not Married,Rent,Employed,lzgpxyit,"MSA, Principle City",1.0,0.0,fcxhlnwr,cmhcxjea
26704,2.0,2.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,lzgpxyit,"MSA, Not Principle City",0.0,0.0,fcxhlnwr,xtkaffoo
26705,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,"<= $75,000, Above Poverty",Married,Rent,Employed,lrircsnp,Non-MSA,1.0,0.0,fcxhlnwr,haliazsg
26706,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,mlyzmhmf,"MSA, Principle City",1.0,0.0,fcxhlnwr,xtkaffoo

In [12]:
#Checking the columns that has Null values from the dataframe created earlier
testf_null_columns = null_testf_Df[null_testf_Df['Null Entries'] != 0].Column.to_list()

#Filling null entries in the training features
for col in testf_null_columns:
        test_features[col]=test_features[col].fillna(test_features[col].mode()[0])

In [13]:
#training_features where null entries are removed
test_features

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,...,income_poverty,marital_status,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation
respondent_id,,,,,,,,,,,,,,,,,,,,,
26707,2.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,...,"> $75,000",Not Married,Rent,Employed,mlyzmhmf,"MSA, Not Principle City",1.0,0.0,atmlpfrs,hfxkjkmi
26708,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Employed,bhuqouqj,Non-MSA,3.0,0.0,atmlpfrs,xqwwgdyp
26709,2.0,2.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,...,"> $75,000",Married,Own,Employed,lrircsnp,Non-MSA,1.0,0.0,nduyfdeo,pvmttkik
26710,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,lrircsnp,"MSA, Not Principle City",1.0,0.0,fcxhlnwr,xtkaffoo
26711,3.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,"<= $75,000, Above Poverty",Not Married,Own,Employed,lzgpxyit,Non-MSA,0.0,1.0,fcxhlnwr,mxkfnird
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53410,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,...,"<= $75,000, Above Poverty",Married,Own,Employed,dqpwygqj,"MSA, Principle City",1.0,1.0,fcxhlnwr,xtkaffoo
53411,3.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,...,Below Poverty,Married,Rent,Employed,qufhixun,Non-MSA,1.0,3.0,fcxhlnwr,vlluhbov
53412,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,Below Poverty,Not Married,Rent,Not in Labor Force,qufhixun,"MSA, Not Principle City",1.0,0.0,fcxhlnwr,xtkaffoo
53413,3.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,"<= $75,000, Above Poverty",Married,Own,Not in Labor Force,bhuqouqj,"MSA, Not Principle City",1.0,0.0,fcxhlnwr,xtkaffoo
53414,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,...,"<= $75,000, Above Poverty",Not Married,Rent,Employed,lrircsnp,"MSA, Principle City",0.0,0.0,fcxhlnwr,xtkaffoo

In [14]:
#Creating Category Columns
cat_columns = training_features.select_dtypes(include=['object']).columns.to_list()
for col in cat_columns:
    training_features[col] = training_features[col].astype('category')
    training_features[col] = training_features[col].cat.codes
    test_features[col] = test_features[col].astype('category')
    test_features[col] = test_features[col].cat.codes

In [15]:
cat_columns

['age_group',
 'education',
 'race',
 'sex',
 'income_poverty',
 'marital_status',
 'rent_or_own',
 'employment_status',
 'hhs_geo_region',
 'census_msa',
 'employment_industry',
 'employment_occupation']

<h3>Creating the Model</h3>

In [16]:
#Importing Necessary Libraries for modelling
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier
from sklearn.ensemble import GradientBoostingClassifier,VotingClassifier
from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier,AdaBoostRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn import svm
from xgboost import XGBClassifier  
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [17]:
#Using the GradientBoostingClassifier and Checking the Accuracy
X_train, X_eval, y_train, y_eval = train_test_split(
    training_features,
    training_labels['h1n1_vaccine'],
    test_size=0.33,
    shuffle=True,
    stratify=training_labels['h1n1_vaccine'],
    random_state=27
)

clf2 = GradientBoostingClassifier(learning_rate=.5,random_state=27)
clf2.fit(X_train, y_train)  
y_pred2 = clf2.predict(X_train)
print("Accuracy:",metrics.accuracy_score(y_train, y_pred2))

Accuracy: 0.8605041077516348

In [18]:
#Using the GradientBoostingClassifier and Checking the Accuracy
clf3 = LogisticRegression(penalty="l2",solver="newton-cg", C=10)
clf3.fit(X_train, y_train)  
y_pred3 = clf3.predict(X_train)
print("Accuracy:",metrics.accuracy_score(y_train, y_pred3))

Accuracy: 0.8339574135136646

In [19]:
#Initializing the training features and labels
X= training_features
y= training_labels

X_train, X_eval, y_train, y_eval = train_test_split(
    X,
    y,
    test_size=0.33,
    shuffle=True,
    stratify=y,
    random_state=27
)

In [20]:
#Using the XGBOOST classifier and Checking the Accuracy
from sklearn import svm
from xgboost import XGBClassifier  
clf1 = XGBClassifier()  
clf1.fit(X_train, y_train)  
y_pred = clf1.predict(X_train)
print("Accuracy:", metrics.accuracy_score(y_train, y_pred))

Accuracy: 0.846588051193204

In [21]:
#Creating all the classifiers used earlier
clf1 = XGBClassifier() 
clf2 = GradientBoostingClassifier(learning_rate=.5,random_state=27)
clf3 = LogisticRegression(penalty="l2",solver="newton-cg", C=10)

#Since the clasifiers tested earlier do not support multiple output, we will use the MultiOutputClassifier of sklearn
mult_classifier = MultiOutputClassifier(estimator=VotingClassifier(estimators=[('ab', clf1), ('gb', clf2), ('lr', clf3)], voting='soft'))

In [22]:
#fitting the multiclassifier created in the previous cell
mult_classifier.fit(X_train,y_train)

MultiOutputClassifier(estimator=VotingClassifier(estimators=[('ab',
                                                              XGBClassifier(base_score=None,
                                                                            booster=None,
                                                                            callbacks=None,
                                                                            colsample_bylevel=None,
                                                                            colsample_bynode=None,
                                                                            colsample_bytree=None,
                                                                            early_stopping_rounds=None,
                                                                            enable_categorical=False,
                                                                            eval_metric=None,
                                                                            gamma=None,
                                                                            gpu_id=None,
                                                                            grow_policy=None,
                                                                            importance_type=None,
                                                                            interaction_constraints=None...
                                                                            max_delta_step=None,
                                                                            max_depth=None,
                                                                            max_leaves=None,
                                                                            min_child_weight=None,
                                                                            missing=nan,
                                                                            monotone_constraints=None,
                                                                            n_estimators=100,
                                                                            n_jobs=None,
                                                                            num_parallel_tree=None,
                                                                            predictor=None,
                                                                            random_state=None,
                                                                            reg_alpha=None,
                                                                            reg_lambda=None, ...)),
                                                             ('gb',
                                                              GradientBoostingClassifier(learning_rate=0.5,
                                                                                         random_state=27)),
                                                             ('lr',
                                                              LogisticRegression(C=10,
                                                                                 solver='newton-cg'))],
                                                 voting='soft'))

<h3>Testing</h3>

In [24]:
test = mult_classifier.predict_proba(test_features)
test

[array([[0.8923695 , 0.10763051],
        [0.95575182, 0.04424818],
        [0.57904239, 0.42095761],
        ...,
        [0.86128638, 0.13871361],
        [0.9683599 , 0.03164011],
        [0.54197385, 0.45802615]]),
 array([[0.8211995 , 0.17880049],
        [0.97401241, 0.02598758],
        [0.20634242, 0.79365758],
        ...,
        [0.72211777, 0.27788222],
        [0.55422216, 0.44577784],
        [0.45715097, 0.54284903]])]

<h3>Converting to CSV</h3>

In [26]:
#Creating csv file
submission_format["h1n1_vaccine"] = test[0][:, 1]
submission_format["seasonal_vaccine"] = test[1][:, 1]
submission_format.to_csv('prelim_exam.csv', index=True)

In [27]:
pd.read_csv("prelim_exam.csv")

       respondent_id  h1n1_vaccine  seasonal_vaccine
0              26707      0.107631          0.178800
1              26708      0.044248          0.025988
2              26709      0.420958          0.793658
3              26710      0.656762          0.833036
4              26711      0.190991          0.580533
...              ...           ...               ...
26703          53410      0.255638          0.538884
26704          53411      0.136729          0.349912
26705          53412      0.138714          0.277882
26706          53413      0.031640          0.445778
26707          53414      0.458026          0.542849

[26708 rows x 3 columns]